### ISSUE TITLE
Design signs, banners and other internal signs for day of event

### ISSUE THREAD

**Issue by erikpmp** [RevolutionVA/Organization#109]
~~18" X 24" sign for the lobby with logo and directions to go upstairs (need Easel)~~
~~18" X 24" sign for the registration desk with logo (need Easel)~~
~~18" X 24" sign for the Sunset Room for Key Note Speaker: Matt Paddock (can attach to room sign)~~

18" X 24" Re-print of original poster with sponsor logos at the bottom (print 2 or 3 of these)

8 1/2" X 11 Lynnhaven Room Schedule
8 1/2" X 11 Chesapeake Ballroom A-B Schedule (Print two of these)
8 1/2" X 11 Chesapeake Ballroom C Schedule
8 1/2" X 11 Horizons Lounge Schedule (Breakfast, snacks, and sponsors)
8 1/2" X 11 Virginia Room Schedule

8 1/2" X 11 Sign for each premiere sponsor table, Lunch sponsor, and Happy Hour sponsor

**Comment by lynnaloo** [comment]
@aureately is going to do the design for these with our existing logos
@aproaps I'm assuming we can get the same price for these if we go through ODU?

**Comment by aproaps** [comment]
I'm not sure how much the 18x24s would be through Fleet where I priced the schedules on regular size paper.

**Comment by aproaps** [comment]
I think I can do 18x24 color posters at Odu but they are $10 each, like a smaller size for the ones we did for nodebots day.

**Comment by lynnaloo** [comment]
@aproaps I'm going to update the budget to figure we're getting the big ones from ODU and the schedules from Fleet. We might just be able to print some of the other smaller signs ourselves on a decent color printer.

**Comment by erikpmp** [comment]
I think this is done now. @lynnaloo ?

**Comment by lynnaloo** [comment]
Not yet. I'll close this when all of the line items are take care of.
